name: attendence_web
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  flare_flutter: ^1.6.2
  #flutter_webview_plugin: 0.3.0+2
  #webview_flutter: 0.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  # Lembrete:
  # Uma importação geral não importa dentro de pastas!
  assets:
    - assets/
    - assets/flare/